### ISSUE TITLE
EAC Game security violation

### ISSUE THREAD

**Issue by ZaweSec** [paradoxwastaken/Poseidon#14]
Hi , i have tried to use this on eac ( Fortnite and apex) , i mapped the driver and started 	Client::Connect(); before eac get loaded but i get security violation, what i can do?

**Comment by win32kbase** [comment]
This happens because the function that is being hooked has been known about for a while and EasyAntiCheat doesn't like it when you tamper with it. 

https://github.com/paradoxwastaken/Poseidon/blob/main/PoseidonClient/sdk.h#L19

The fix is to, of course, find another similar function which is not actively monitored and modify the code to work with said function.

edit: Apparently the driver unhooks this, read the issue posted below

**Comment by KaylinOwO** [comment]
An issue about this was already made (https://github.com/paradoxwastaken/Poseidon/issues/7), you just have to connect to the driver before you start the AC/game.

**Comment by ZaweSec** [comment]
> An issue about this was already made (#7), you just have to connect to the driver before you start the AC/game.

Thanks , i already tried but nothing changed.
