### ISSUE TITLE
working only once?

### ISSUE THREAD

**Issue by ghost** [paradoxwastaken/Poseidon#4]
everything in the driver only seems to work once..? i removed all the bools for "do once" type behavior, but it still doesnt work properly. for example, i can get the baseaddress of notepad lets say, but if i try to do anything else, the usermode just is blank and doesnt do anything. even after i restart the usermode, i cant do any more requests, its like ive used a one time token haha (i have to remap the driver for it to work again). im mapping with kdmapper (latest build), and ive tried everything but im not sure how to fix this.. i tried adding you on discord but you havent yet accepted my request (its been a few days now). this is a very interesting project btw, good work, just a bit stuck on this slight hiccup.

**Comment by raywave** [comment]
as far I found, there is two ways:
I. you need to paste `InterlockedExchangePointer((PVOID*)gFunc, (PVOID)EnumerateDebuggingDevicesHook);` after https://github.com/paradoxwastaken/Poseidon/blob/main/Poseidon/sdk.h#L18 and always finish Usermode with **Exit** status. (it's more undetectable way, but buggy: if your usermode crash or you finish without Exit status - you won't be able to communicate)
II. you need to remove https://github.com/paradoxwastaken/Poseidon/blob/main/Poseidon/sdk.h#L16 (its removing hook from function) - it's less undetectable way, but it may cause memory loss (idk?), because if your usermode crash or you don't exit with Exit status, there will be endless loop (more and more with all restarts)
i don't know maybe there's any another way of doing this, i will try to do another way

upd: in addition to all methods try to re-check is application process exists in [this loop](https://github.com/paradoxwastaken/Poseidon/blob/main/Poseidon/sharedmemory.h#L149) and if it's not just return, it will fix their disadvantages.

**Comment by sondernextdoor** [comment]
> II. you need to remove https://github.com/paradoxwastaken/Poseidon/blob/main/Poseidon/sdk.h#L16 (its removing hook from function) - it's less undetectable way, but it may cause memory loss (idk?), because if your usermode crash or you don't exit with Exit status, there will be endless loop (more and more with all restarts)

This would allow you to restart the client and regain a connection with the driver at will, but like you said, it's very detectable and may cause a bunch of infinite loops running in the kernel if you fail to exit properly. If you're fine with leaving a permanent hook in the kernel, then it'd be much better to just use the hook as the communication method.

If you really want the ability to close and reopen the client at will, then the best solution is probably to use a third process for the usermode thread and allocated memory. This is actually how I originally wrote this project, but I scrapped it for some reason that I can't remember lol (I originally wrote this a year ago).

I've made a couple changes, mainly to allow for the client to be terminated gracefully while in use. You'll still need to remap the driver after closing it though. Closing this issue as Eternal's issue has been resolved over Discord.
