### ISSUE TITLE
Violations

### ISSUE THREAD

**Issue by elchoky** [paradoxwastaken/Poseidon#7]
For test purpose i test on simple game with EAC.
Should work, but include that is a super low game.
With EAC. Include with a simple BaseAddress read from the process and all running correct, the EAC end at same.
Is detected or need another type of security to work on eac

**Comment by sondernextdoor** [comment]
Just tested on EAC (Fortnite), it works fine. As stated in the readme, it needs to be set up before the anticheat. This includes mapping the driver, starting the client, and calling Client::Connect() all before the anticheat is running.

The security violation EAC is giving is due to the detection of the temporary hook in the kernel. This gets unhooked when you call Client::Connect(), which is why it's imperative that you do that before the anticheat is running.

In addition, the driver isn't meant to be fully UD in its current state, only the communication method is. There's still a big pool of allocated memory in the kernel that will likely result in a flag if it's not freed.

**Comment by elchoky** [comment]
Yeah my error, thanks for the reply for some reaso before testing and after i build my detected proccess in the driver, to find when the procces is running i move my conection fk stp* that i am.

**Comment by elchoky** [comment]
Any case looks like work perfect, just movin that and tested, you talk about another part of the kernel.
There is any help point where i should start looking?

**Comment by sondernextdoor** [comment]
glad everything's working good! :D 

this thread has a bunch of info + some code about clearing the big pool table: https://www.unknowncheats.me/forum/anti-cheat-bypass/428976-removing-mapped-driver-systembigpoolinformation.html

It's probably not enough to get banned, but it's definitely suspicious enough to warrant further investigation by EAC.

**Comment by elchoky** [comment]
Idk but i think i dont doe nothing wrong yet.
But looks like the response from the driver affect some functions for me.
Where normal without driver  work correct, while read, looks like take some ms, that uncontroll my loops

**Comment by zqbake** [comment]
> Just tested on EAC (Fortnite), it works fine. As stated in the readme, it needs to be set up before the anticheat. This includes mapping the driver, starting the client, and calling Client::Connect() all before the anticheat is running.
> 
> The security violation EAC is giving is due to the detection of the temporary hook in the kernel. This gets unhooked when you call Client::Connect(), which is why it's imperative that you do that before the anticheat is running.
> 
> In addition, the driver isn't meant to be fully UD in its current state, only the communication method is. There's still a big pool of allocated memory in the kernel that will likely result in a flag if it's not freed.

How to mapping the driver? any documents ?
